circuit:
  description: A quantum circuit made of qubit rows. Each row contains ordered
    line segments. A segment may contain no gate, a standard gate, or a custom
    2x2 matrix gate.
  qubits:
    - id: q0
      label: "|0>"
      y: 160
      segments:
        - id: s0
          gate: none
        - id: d894e686-eafa-488c-b9c7-7914d85ece68
          gate: H
        - id: 8645d494-44e7-4318-a41a-dfd2c14af5af
          gate: OTHER
          matrix:
            x1: 1
            x2: 0
            x3: 0
            x4: 1
        - id: c89adf8b-ec68-422d-a0ce-84087edb1f97
          gate: H
        - id: d4942f72-a9d4-463e-9d50-94151ba66962
          gate: none
    - id: q1
      label: "|0>"
      y: 250
      segments:
        - id: aaba24ed-4f49-464c-96a5-800c05909dfc
          gate: none
        - id: b2e9f15b-bd8a-4e1b-a42a-0b1f1fd81f4f
          gate: H
        - id: 66141b90-8213-422b-976f-2b7ad10219b6
          gate: OTHER
          matrix:
            x1: 1
            x2: 0
            x3: 0
            x4: 1
        - id: 55d311bf-52e1-4cf9-88f0-002a8cda4087
          gate: H
    - id: q2
      label: "|0>"
      y: 340
      segments:
        - id: 8a7ac3b6-7caf-4b86-bc1e-012a45f5dbe2
          gate: none
        - id: 1712f513-f13d-4db0-bb79-b6678eddd442
          gate: X
        - id: 74d29601-c266-4013-8a5c-cd9cec81a8bc
          gate: none
