circuit:
  description: A quantum circuit made of qubit rows. Each row contains ordered
    line segments. A segment may contain no gate, a standard gate, or a custom
    2x2 matrix gate.
  qubits:
    - id: q0
      label: "|0>"
      y: 160
      segments:
        - id: s0
          gate: X
        - id: 81214239-43fb-4f94-9bf5-ce96fb813887
          gate: H
        - id: a4a36f4e-bd3d-446f-8e95-1eee380d8162
          gate: none
        - id: 25421664-f23d-4951-b805-b199aa11533a
          gate: H
        - id: 7722727e-3585-4429-a5c8-b90bb50b383f
          gate: MEASURE
    - id: q1
      label: "|0>"
      y: 250
      segments:
        - id: 2d2ffd38-5b5e-44bc-ba3a-9e4c0c4aab6d
          gate: none
        - id: 246f974a-01e2-4a55-a61a-3efc37cad080
          gate: H
        - id: 46ff71fb-3c43-4139-a406-d8a2db2953af
          gate: UF
          uf:
            function: const1
            x_bits:
              - q0
        - id: 017acf67-8b98-4c53-9814-d5714e12e534
          gate: none
    - id: q2
      label: "|0>"
      y: 340
      segments:
        - id: 0cb7212d-6884-4176-8559-857bdb4b5ff3
          gate: none
        - id: 5ae2f1bc-8423-498c-b616-51475525acec
          gate: H
        - id: 5cd95de0-bf82-4934-821b-c65029dd5b6f
          gate: UF
          uf:
            function: const0
            x_bits:
              - q1
